### PR TITLE
Wamphys tendecies and include p8 ccpp suites

### PR DESCRIPTION
**Pull request by WChen-NOAA**

### CODE REVIEW

**Comment by WChen-NOAA** [comment]
#4 would be the correct pull request. I may do something wrong on #3

**Comment by akubaryk** [comment]
> #4 would be the correct pull request. I may do something wrong on #3

#3 has already been closed, you mean #5 is the mistake pull request? It doesn't seem there's much difference between this one and #4.

**Comment by vyudinspb** [comment]
Wen and Adam,

It looks good, thanks for putting it. I would like to see the results of trial runs and wrkdir.

Some clean up we can perform later, avoiding 
dudt_wamion = dudt_ion ,   dtdt_wamrad = wtot ...etc....,
as well as clean up from new Svetlana's branch.

I expect you put appropriate changes in the new "suite"  under
FV3/ccpp....  Good work !!!

For GSMWAM we can put the netcdf-diagnostics of corresponding tendencies
and tides. I have a research version of GSMWAM on Hera. 

It requires addition of ~dozen subs
(in gsm/physics and gsm/dynamics and phys/idea....).

**Comment by akubaryk** [comment]
@vyudinspb can you point me to that code? Would be useful to merge in the diagnostics code to a branch off the operational version if possible.

**Comment by SvetlanaKarol-NOAA** [comment]
Wen, thank you for diagnostics of WAMPHYS tendencies.
I have some comments.
Line 46 in GFS_WAM_generic_post.F90
 if (ldiag3d .and. flag_for_wam_generic_tend .and. .not.do_wamphys_diag) 
This condition is not executed, for do_wamphys_diag='.true.', which is a default for wamphys. For do_wamphys_diag='.false.', wamphys_run returns "zero" tendencies.
Maybe it will be good to use one flag for "flag_for_wam_generic_tend" , "do_wamphys_diag" .
Could you point to your work directory, where you write ncdf files with tendencies?
How do you get the output, from dtend-container or individual tendencies from 
wamphys_post.F90?

**Comment by WChen-NOAA** [comment]
Hi Svetlana,
Currently, the GFS_WAM-generic_post.F90 can be removed and added in the CCPP suite. 
I put it there for future consideration  if there is any other diagnostic fields needs to be output.
the  (ldiag3d .and. flag_for_wam_generic_tend .and. not.do_wamphys_diag ) only for tendencies. 
while if do_wamphys_diag=.true. could includes tendencies and other diagnostic fields . 
I forgot updating  the diag_table. I will send an email to you later, and try if I can adding the diag_table to this pull request.

**Comment by WChen-NOAA** [comment]
Hi, I have removed the useless scripts and updated the config/diag_table files.
And I think on Hera the rt.sh could works.
My sorc on Hera /scratch1/NCEPDEV/global/Wen.Chen/FV3WAM/ufs-weather-model-wamphys-beta3.2_test
rundir /scratch1/NCEPDEV/stmp2/Wen.Chen/FV3_RT/rt_190622/
I have sent my develop sorc dir to Svetlana via email.
I have any other comments, pls feel free to let me know.

**Pull request closed without merging**
